### ISSUE TITLE
NMS Vendor request: Register an IANA enterprise number

### ISSUE THREAD

**Issue by smeusekentik** [CraftComputing/ProjectAxeEffect#2]
https://www.iana.org/assignments/enterprise-numbers/assignment/apply/

NMS vendor here. It would be greatly appreciated by all the worlds NMS vendors for you to register for a IANA enterprise number and publish unique sysObjectIDs for your products (if you end up having multiple, but even if you only have one). 

This also gives you the benefit of being able to structure your own MIB data if you ever device to go beyond temp/humidity. 

I'm fairly sure the registration is free.

**Comment by CraftComputing** [comment]
I have submitted a request to IANA. As soon as I have a number, I will post it here.

**Comment by CraftComputing** [comment]
Craft Computing PEN: 62179

**Comment by smeusekentik** [comment]
Awesome, adding support into Kentik NMS now!

-Steve
