### ISSUE TITLE
Guidance needed on serial driver for Windows

### ISSUE THREAD

**Issue by aolsonesxtech** [CraftComputing/ProjectAxeEffect#5]
Plugged in a mac or linux, usb serial is detected fine, no issues.  when plugged into a couple of different windows machines, device is detected as "reset" with no driver.  maybe we can add a section for rough guidance on where to get the correct driver if it's not plug and play.  Not sure if this is just a me issue or something that I might not be aware of with these Pi boards.

**Comment by CraftComputing** [comment]
The serial driver should be plug and play with basically any system. If you're not getting a serial connection, I'd recommend re-flashing the unit.

Please download the latest firmware (v1.3).

Press and hold the 'reset' button on top of the case, while connecting Axe Effect to your PC via USB.

Axe Effect should appear as a USB drive. Copy over the v1.3.uf2 file.

Axe Effect will automatically install and reboot. If working properly, you should be able to connect via serial.

Please let me know if this resolved your issue, or if we need to dig a bit deeper into why it's not working for you.

-Jeff

**Comment by Lucannus87** [comment]
Jeff, I seem to have this issue as well. Not sure how aolsonsxtech got it working. I posted with pictures of my setup on the subreddit. https://new.reddit.com/r/CraftComputing/comments/1egvd1h/axe_effect_question_maybe_issue/

**Comment by aolsonesxtech** [comment]
@Lucannus87 check your comports too when you plug it in, it's showing as 2 deivces and I missed the additional com port that showed up as well.

**Comment by Lucannus87** [comment]
> @Lucannus87 check your comports too when you plug it in, it's showing as 2 deivces and I missed the additional com port that showed up as well.

It comes up as COM5, but i cannot connect to it using Putty with the given config settings.
