### ISSUE TITLE
Uncompiled Source

### ISSUE THREAD

**Issue by scline** [CraftComputing/ProjectAxeEffect#8]
Is it possible to add the uncompiled files for the firmwares vs just having `*.uf2`? This would allow others to contribute and add to the project or simply tinker without building from the ground up.

**Comment by aolsonesxtech** [comment]
He said in the video that this is not a open source project, just open source documentation, so likely won't be getting this at this time :)  or at least that was my interpretation.  maybe if this goes well as a business, they can opensource the firmware.

**Comment by scline** [comment]
Ah fair, will close this then and thanks for the comment!
